execute @s [family=mob] ~ ~ ~ scoreboard players add @p[r=16] score.kills 1
execute @s [tag=!dead,type=axolotl] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=bat] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=bee] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=blaze] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=cat] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=cave_spider] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 3
execute @s [tag=!dead,type=chicken] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=cow] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=creeper] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 3
execute @s [tag=!dead,type=dolphin] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=donkey] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=elder_guardian] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 50
execute @s [tag=!dead,type=ender_dragon] ~ ~ ~ scoreboard players add @a[r=500] realm.exp 500
execute @s [tag=!dead,type=enderman] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=endermite] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=evocation_illager] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=cod] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=fox] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=glow_squid] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=goat] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1 
execute @s [tag=!dead,type=guardian] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=hoglin] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=horse] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 3
execute @s [tag=!dead,type=iron_golem] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=llama] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=magma_cube] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=mooshroom] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=mule] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=ocelot] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=panda] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=parrot] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=phantom] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=pig] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=piglin_brute] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=piglin] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=pillager] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=polar_bear] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 3
execute @s [tag=!dead,type=pufferfish] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=rabbit] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=ravager] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 4
execute @s [tag=!dead,type=salmon] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=sheep] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=shulker] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=silverfish] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=skeleton_horse] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=skeleton] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=slime] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=snow_golem] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=spider] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 4
execute @s [tag=!dead,type=squid] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=stray] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=strider] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=tropicalfish] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=turtle] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=vex] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=villager] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=vindicator] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=wandering_trader] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2
execute @s [tag=!dead,type=witch] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=wither_skeleton] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 4
execute @s [tag=!dead,type=wither] ~ ~ ~ scoreboard players add @a[r=200] realm.exp 500
execute @s [tag=!dead,type=wolf] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 1
execute @s [tag=!dead,type=zoglin] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 5
execute @s [tag=!dead,type=zombie_horse] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=zombie_pigman] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=zombie_villager] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 6
execute @s [tag=!dead,type=zombie] ~ ~ ~ scoreboard players add @p[r=16] realm.exp 2